version: '3.9'

services:
  backend:
    build: ./comment-app-backend
    ports:
      - '5000:5000'
    env_file:
      - ./comment-app-backend/.env
    volumes:
      - ./comment-app-backend:/app
    restart: unless-stopped

  frontend:
    build: ./comment-app-frontend
    ports:
      - '5173:5173'
    depends_on:
      - backend
    env_file:
      - ./comment-app-frontend/.env
    # volumes:
    #   - ./comment-app-frontend:/app
    restart: unless-stopped
